name: Tests

on: [pull_request]

jobs:
  tests: 
    name: Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Docker Compose
        run: |
            docker-compose up -d
            sleep 5

      - name: Composer Install
        run: |
            docker run --rm --volume "$(pwd)":/app composer install --ignore-platform-reqs --optimize-autoloader --no-plugins --no-scripts --prefer-dist
      
      - name: Run Tests
        run: |                
            docker ps
            composer test
            composer analyze
            